version: '3.7'

x-datanode_base: &datanode_base
  image: datanode
  networks:
    - bridge

services:
  namenode:
    image: namenode
    container_name: namenode
    hostname: namenode
    ports:
      - '9098:9870' # namenode web UI
    volumes:
      - namenode:/opt/hadoop/dfs/name # namenode data mount
      - namenode:/opt/spark/eventLog # spark history log data mount
      - namenode:/opt/hadoop/yarn/timeline # yarn timeline data mount
    networks:
      - bridge
  #      hs_bridge:
  #        ipv4_address: 192.0.0.5

  datanode01:
    <<: *datanode_base
    container_name: datanode01
    hostname: datanode01
    volumes:
      - datanode01:/opt/hadoop/dfs/data
      - datanode01:/opt/hadoop/yarn/data
      - namenode:/opt/spark/eventLog
  #    networks:
  #      hs_bridge:
  #        ipv4_address: 192.0.0.2
  resourcemanager:
    image: resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - '9099:8088'
    networks:
      - bridge
  #   volumes:
  #     - namenode:/opt/hadoop/yarn/data
  #      hs_bridge:
  #        ipv4_address: 192.0.0.10

  yarntimelineserver:
    image: yarntimelineserver
    container_name: yarntimelineserver
    hostname: yarntimelineserver
    ports:
      - '9096:8188'
    networks:
      - bridge
    volumes:
      - namenode:/opt/hadoop/yarn/timeline
  #      hs_bridge:
  #        ipv4_address: 192.0.0.12

  sparkhistoryserver:
    image: sparkhistoryserver
    container_name: sparkhistoryserver
    hostname: sparkhistoryserver
    ports:
      - '9093:18080'
    depends_on:
      - namenode
      - resourcemanager
    volumes:
      - namenode:/opt/spark/eventLog
    networks:
      - bridge

  zeppelin:
    image: zeppelin
    container_name: zeppelin
    hostname: zeppelin
    ports:
      - '9097:8080'
    networks:
      - bridge
    volumes:
      - namenode:/opt/spark/eventLog
      - /Users/seongcheollee/Documents/env/hadoop/zeppelin/notebook:/zeppelin-0.10.1-bin-all/notebook
      - /Users/seongcheollee/Documents/env/hadoop/data:/testdata

volumes:
  namenode:
  datanode01:
  datanode02:
  datanode03:

networks:
  bridge:
#networks:
#  hs_bridge:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.0.0.0/16
